site_name: "Jeu sérieux : Phone Impact"
site_url: https://learninglab.gitlabpages.inria.fr/serious-game/smartphone
repo_url: https://gitlab.inria.fr/learninglab/serious-game/smartphone
repo_name: Source
use_directory_urls: false
theme:
  logo: img/logo.png
  name: material
  custom_dir: custom/
  features:
    - navigation.tabs
    - navigation.footer
  palette:
    primary: custom
    accent: amber
extra_css:
  - assets/extra.css
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css
extra_javascript:
  - assets/extra.js
extra:
  generator: false
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - meta
  - toc:
      permalink: true
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.tabbed
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.smartsymbols
  - pymdownx.arithmatex:
      generic: true
plugins:
  - awesome-pages
  - search
  - macros
  - page-to-pdf:
      disableOnServe: true
      displayHeaderFooter: true
      printBackground: true
      headerTemplate: '<header style="width:100%;font-size:10px;font-weight:600;color:white;background:#4051b5;margin-top:-20px;padding:15px;padding-bottom:10px;-webkit-print-color-adjust: exact">
                      <span style="display:inline-block;vertical-align:middle;margin-top:-4px;margin-left:10px;font-family: Verdana,Arial,sans-serif;">{{config["site_name"]}}</span>
                    </header>'
      footerTemplate: '<footer style="position:relative;width:100%;font-size:8px;color:#999999;margin:10px 20px;-webkit-print-color-adjust: exact">
                      <span style="font-family: Courier,monospace;">Resource designed by Inria Learning Lab | CC BY-NC-SA 4.0 | 2023</span>
                      <span class="page" style="position:absolute;bottom:0;right:0;font-family: Courier,monospace;">
                        <span class="pageNumber"></span>/<span class="totalPages"></span>
                      </span>
                    </footer>'

