authors:
    nathan:
        name: Nathan Viaud
        description: Développeur
        avatar: https://avatars.githubusercontent.com/u/79544144?v=4
        url: https://github.com/NathanViaud
    madeline:
        name: Madeline Montigny
        description: Ingénieure pédagogique
        avatar: docs/img/MadelineMontigny.jpg
        url: https://www.linkedin.com/in/madelinemontigny/
    sherazade:
        name: Sherazade Djeballah
        description: Ingénieure pédagogique
        avatar: docs/img/Sherazade.jpeg
        url: https://www.linkedin.com/in/sherazade-djeballah-6a8759233/