authors:
    nathan:
        name: Nathan Viaud
        description: Développeur
        avatar: https://avatars.githubusercontent.com/u/79544144?v=4
        url: https://github.com/NathanViaud
    madeline:
        name: Madeline Montigny
        description: Ingénieure pédagogique
        avatar: https://media.licdn.com/dms/image/v2/D4D03AQGCk_gTLKwoqA/profile-displayphoto-shrink_400_400/B4DZPA8GR.HYAg-/0/1734108800751?e=1740009600&v=beta&t=_adz2ZhMVXuEHdwVY3HPdy1Lr6fZJ5hw_-b8Vu4KVZw
        url: https://www.linkedin.com/in/madelinemontigny/
    sherazade:
        name: Sherazade Djeballah
        description: Ingénieure pédagogique
        avatar: docs/img/Sherazade.jpeg
        url: https://www.linkedin.com/in/sherazade-djeballah-6a8759233/