authors:
    madeline:
        name: Madeline Montigny
        description: Ingénieure pédagogique
        avatar: blog/img/MadelineMontigny.jpg
        url: https://www.linkedin.com/in/madelinemontigny/
    sherazade:
        name: Sherazade Djeballah
        description: Ingénieure pédagogique
        avatar: blog/img/Sherazade.jpeg
        url: https://www.linkedin.com/in/sherazade-djeballah-6a8759233/
    sabah:
        name: Sabah Khalfa
        description: Ingénieure pédagogique
        avatar: blog/img/SabahKhalfa.jpeg
        url: https://www.linkedin.com/in/sabah-khalfa-ab24749/
